platform:
  - x64
  - x86

environment:
  matrix:

# VS 2012
  - BUILD_TYPE: cmake
    VS_VERSION: Visual Studio 11 2012

# VS 2013
  - BUILD_TYPE: cmake
    VS_VERSION: Visual Studio 12 2013

# VS 2015
  - BUILD_TYPE: cmake
    VS_VERSION: Visual Studio 14 2015

shallow_clone: true

build_script:
  - echo build_script
  - if "%BUILD_TYPE%" == "cmake" if "%platform%" == "x64" SET VS_FULL=%VS_VERSION% Win64
  - if "%BUILD_TYPE%" == "cmake" if "%platform%" == "x86" SET VS_FULL=%VS_VERSION%
  - if "%BUILD_TYPE%" == "cmake" echo "%VS_FULL%"
  - if "%BUILD_TYPE%" == "cmake" cmake -G "%VS_FULL%" . -DBUILD_SHARED_LIBS=ON
  - if "%BUILD_TYPE%" == "cmake" cmake --build . --config Release
  - if "%BUILD_TYPE%" == "cmake" cmake --build . --config Release --target package

test_script:
  - echo test_script
  
artifacts:
  - path: dist\*
    name: package

deploy:
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: pAqZWDE6h3dlvBzOw9g3s2OYlB/+nd+yZebVru/wmHsUeFXo2KiP1baQ9klc/uLO
  artifact: package
  draft: true
  on:
    appveyor_repo_tag: true
